/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TABLES = 0;

  /**
   * The feature id for the '<em><b>View Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VIEW_MODELS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ViewModelImpl <em>View Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ViewModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getViewModel()
   * @generated
   */
  int VIEW_MODEL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW_MODEL__FIELDS = 1;

  /**
   * The number of structural features of the '<em>View Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTable()
   * @generated
   */
  int TABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__ITEMS = 1;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstructItemImpl <em>Abstruct Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AbstructItemImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstructItem()
   * @generated
   */
  int ABSTRUCT_ITEM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRUCT_ITEM__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstruct Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRUCT_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.Int32ItemImpl <em>Int32 Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.Int32ItemImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt32Item()
   * @generated
   */
  int INT32_ITEM = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT32_ITEM__NAME = ABSTRUCT_ITEM__NAME;

  /**
   * The number of structural features of the '<em>Int32 Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT32_ITEM_FEATURE_COUNT = ABSTRUCT_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StringItemImpl <em>String Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StringItemImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringItem()
   * @generated
   */
  int STRING_ITEM = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ITEM__NAME = ABSTRUCT_ITEM__NAME;

  /**
   * The number of structural features of the '<em>String Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ITEM_FEATURE_COUNT = ABSTRUCT_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BindingFieldImpl <em>Binding Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BindingFieldImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBindingField()
   * @generated
   */
  int BINDING_FIELD = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FIELD__TABLE = 1;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FIELD__ITEM = 2;

  /**
   * The number of structural features of the '<em>Binding Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FIELD_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tables</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getTables()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getViewModels <em>View Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>View Models</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getViewModels()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ViewModels();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ViewModel <em>View Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>View Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.ViewModel
   * @generated
   */
  EClass getViewModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ViewModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ViewModel#getName()
   * @see #getViewModel()
   * @generated
   */
  EAttribute getViewModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.ViewModel#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.xtext.example.mydsl.myDsl.ViewModel#getFields()
   * @see #getViewModel()
   * @generated
   */
  EReference getViewModel_Fields();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Table#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see org.xtext.example.mydsl.myDsl.Table#getItems()
   * @see #getTable()
   * @generated
   */
  EReference getTable_Items();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AbstructItem <em>Abstruct Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstruct Item</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstructItem
   * @generated
   */
  EClass getAbstructItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.AbstructItem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstructItem#getName()
   * @see #getAbstructItem()
   * @generated
   */
  EAttribute getAbstructItem_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Int32Item <em>Int32 Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int32 Item</em>'.
   * @see org.xtext.example.mydsl.myDsl.Int32Item
   * @generated
   */
  EClass getInt32Item();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.StringItem <em>String Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Item</em>'.
   * @see org.xtext.example.mydsl.myDsl.StringItem
   * @generated
   */
  EClass getStringItem();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BindingField <em>Binding Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binding Field</em>'.
   * @see org.xtext.example.mydsl.myDsl.BindingField
   * @generated
   */
  EClass getBindingField();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.BindingField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.BindingField#getName()
   * @see #getBindingField()
   * @generated
   */
  EAttribute getBindingField_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.BindingField#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see org.xtext.example.mydsl.myDsl.BindingField#getTable()
   * @see #getBindingField()
   * @generated
   */
  EReference getBindingField_Table();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.BindingField#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see org.xtext.example.mydsl.myDsl.BindingField#getItem()
   * @see #getBindingField()
   * @generated
   */
  EReference getBindingField_Item();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TABLES = eINSTANCE.getModel_Tables();

    /**
     * The meta object literal for the '<em><b>View Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__VIEW_MODELS = eINSTANCE.getModel_ViewModels();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ViewModelImpl <em>View Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ViewModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getViewModel()
     * @generated
     */
    EClass VIEW_MODEL = eINSTANCE.getViewModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIEW_MODEL__NAME = eINSTANCE.getViewModel_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIEW_MODEL__FIELDS = eINSTANCE.getViewModel_Fields();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE__ITEMS = eINSTANCE.getTable_Items();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstructItemImpl <em>Abstruct Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AbstructItemImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstructItem()
     * @generated
     */
    EClass ABSTRUCT_ITEM = eINSTANCE.getAbstructItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRUCT_ITEM__NAME = eINSTANCE.getAbstructItem_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.Int32ItemImpl <em>Int32 Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.Int32ItemImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt32Item()
     * @generated
     */
    EClass INT32_ITEM = eINSTANCE.getInt32Item();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StringItemImpl <em>String Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StringItemImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStringItem()
     * @generated
     */
    EClass STRING_ITEM = eINSTANCE.getStringItem();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BindingFieldImpl <em>Binding Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BindingFieldImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBindingField()
     * @generated
     */
    EClass BINDING_FIELD = eINSTANCE.getBindingField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINDING_FIELD__NAME = eINSTANCE.getBindingField_Name();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING_FIELD__TABLE = eINSTANCE.getBindingField_Table();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING_FIELD__ITEM = eINSTANCE.getBindingField_Item();

  }

} //MyDslPackage
