/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.StringItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringItemImpl extends AbstructItemImpl implements StringItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.STRING_ITEM;
  }

} //StringItemImpl
